baseurl: "https://xiangyx7.netlify.app/"
languageCode: "en-us"
title: "Yaoxin Xiang | 向尧新"
theme: "hugo-xmin"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"
hasCJKLanguage: true
enableEmoji: true

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home/主页
      url: ""
      weight: 1
    - name: About/关于
      url: "about/"
      weight: 2
    - name: Tags/标签
      url: "tags/"
      weight: 3

params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; [Yaoxin Xiang](https://xiangyx7.netlify.app/) 2021 -- 2021 | [Github](https://github.com/xiangyx)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
